//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KevinDBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KevinTB
    {
        public int learnerID { get; set; }
        public string learnerName { get; set; }
        public string strongestSkill { get; set; }
        public Nullable<int> numberOfLanguages { get; set; }
        public string favoriteSubject { get; set; }
        public string enrolledProgram { get; set; }
    }
}
